services:
  pigeonhunter:
    build: .
    image: pigeonhunter:latest
    container_name: pigeonhunter
    volumes:
      - ./config_data:/root/.config/PigeonHunter
      - ./logs:/app/logs # Opcional: si quieres tener acceso a los logs fuera
    restart: unless-stopped
    stdin_open: true
    tty: true